# Generated by Django 4.2 on 2025-06-28 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shown to customer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='ONU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g. AA:BB:CC:DD:EE:FF)', regex='^([0-9A-Fa-f]{2}[:\\-]){5}([0-9A-Fa-f]{2})$')])),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('vendor', models.CharField(choices=[('Huawei', 'Huawei'), ('ZTE', 'ZTE'), ('Other', 'Other')], default='Other', max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('online', models.BooleanField(default=False)),
                ('last_inform', models.DateTimeField(blank=True, null=True)),
                ('rx_power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(10)])),
                ('tx_power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-40), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='core.customerinfo')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
    ]
