# Generated by Django 4.2 on 2025-06-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onu',
            name='password',
            field=models.CharField(blank=True, help_text='ONU admin password', max_length=128),
        ),
        migrations.AddField(
            model_name='onu',
            name='username',
            field=models.CharField(blank=True, help_text='ONU admin username', max_length=64),
        ),
    ]
